spring.application.name=bikestore
spring.data.mongodb.uri=mongodb+srv://admin:admin123456@cluster0.kf2xbd8.mongodb.net/bikestores?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=bikestores

# Server Port
server.port=8080

# Logging
logging.level.org.springframework=INFO
logging.level.com.example.bikestore=DEBUG

# Enable Lombok annotation processing
spring.devtools.restart.enabled=true