spring.application.name=bikestore
spring.data.mongodb.uri=mongodb://localhost:27017/bike_store
spring.data.mongodb.database=bike_store

# Server Port
server.port=8080

# Logging
logging.level.org.springframework=INFO
logging.level.com.example.bikestore=DEBUG

# Enable Lombok annotation processing
spring.devtools.restart.enabled=true